export const ESPECIALIZACIONES = [
  'Developer',
  'SysAdmin / DevOps / SRE',
  'Manager / Director',
  'Technical Leader',
  'QA / Tester',
  'BI Analyst / Data Analyst',
  'HelpDesk',
  'Architect',
  'Data Engineer',
  'Data Scientist',
  'Consultant',
  'UX',
  'Infosec',
  'Business Analyst',
  'Networking',
  'Recruiter / HR',
  'Functional Analyst',
  'DBA',
  'Technical Support',
  'Scrum Master',
  'Designer',
  'VP / C-Level',
  'Sales / Pre-Sales',
  'Middleware',
  'Finance',
  'Storage / Backup',
  'Docente',
  'Project Manager',
  'Administrativo',
  'Administrativo',
  'Technical Writer',
];
