version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: salaries
    ports:
      - '5432:5432'
  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 5050
    volumes:
       - ./pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - '5050:5050'
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'host.docker.internal:5432:*:root:root' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"

