module.exports = {
  tabWidth: 2,
  useTabs: false,
  singleQuote: true,
  semi: true,
  bracketSpacing: true,
  arrowParens: 'avoid',
  trailingComma: 'es5',
  bracketSameLine: true,
  printWidth: 80,
  plugins: [
    'prettier-plugin-tailwindcss',
    'prettier-plugin-organize-imports',
    '@trivago/prettier-plugin-sort-imports',
  ],
  endOfLine: 'lf',
  importOrder: [
    '^@angular/material/(.*)$',
    '^@angular/cdk/(.*)$',
    '^@angular/(.*)$',
    '^[./]',
  ],
  importOrderParserPlugins: ['typescript', 'decorators'],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};
